---
- hosts: all
  become: true
  tasks: 
   
  - name: update repository index
    apt: 
     update_cache: yes

  - name: install apache2 package
    ansible.builtin.apt:
      name: apache2  
     # state: absent
  
  - name: add php support for apache
    ansible.builtin.apt:
       name: libapache2-mod-php
    #   state: absent