---
- hosts: all
  become: true
  pre_tasks:

  - name: update repo cache (centOS)
    tags: always
    ansible.builtin.yum:
     update_cache: yes
    changed_when: false   # as this play will always update and we won't want it to always output
    when: ansible_distribution == "CentOS"

  - name: update repo cache ( Debian)
    tags: always
    ansible.builtin.apt:
     update_cache: yes
    changed_when: false  # as this play will always update and we won't want it to always output
    when: ansible_distribution == "Debian"
    
- hosts: all
  become: true
  roles: 
   - base

- hosts: workstations
  become: true
  roles:
   - workstations

- hosts: web_servers
  become: true
  roles:
   - web_servers

- hosts: db_servers
  become: true
  roles:
   - db_servers

- hosts: file_servers
  become: true
  roles:
   - file_servers