---
- hosts: all
  become: true
  pre_tasks:

  - name: install updates (centOS)
    tags: always
    ansible.builtin.yum:
     update_only: yes
     update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install updates ( Debian)
    tags: always
    ansible.builtin.apt:
     upgrade: dist
     update_cache: yes
    when: ansible_distribution == "Debian"
 
- hosts: web_servers
  become: true
  tasks:
    - name: install apache and php for Debian servers
      tags: apache,apache2,debian
      ansible.builtin.apt:
        name: 
         - apache2
         - libapache2-mod-php
        state: latest
      when: ansible_distribution == "Debian"

    - name: install httpd and php for CentOS servers
      tags: centos,httpd
      ansible.builtin.yum:
        name: 
         - httpd
         - php
        state: latest
      when: ansible_distribution == "CentOS"

    - name: copy default html file for site
      tags: apache,apache2,httpd
      ansible.builtin.copy:
       src: /home/admin/webpage/default_site.html
       dest: /var/www/html/index.html
       owner: root
       group: root
       mode: 0644
  
- hosts: workstations
  become: true
  tasks:
    - name: install unzip
      package:
        name: unzip

    - name: install terraform
      unarchive:
        src: https://releases.hashicorp.com/terraform/1.4.4/terraform_1.4.4_linux_amd64.zip
        dest: /usr/local/bin
        remote_src: yes
        mode: 0755
        owner: root
        group: root


- hosts: db_servers
  become: true
  tasks:
    - name: install mariadb package (CentOS)
      tags: mariadb,centos,db
      ansible.builtin.yum:
       name: mariadb
       state: latest
      when: ansible_distribution == "CentOS"

    - name: install mariadb package on (Debian)
      tags: db,mariadb,debian
      ansible.builtin.apt:
       name: mariadb-server
      when: ansible_distribution == "Debian"

- hosts: file_servers
  become: true
  tasks:
    - name: install samba package
      tags: samba
      package: 
       name: samba
       state: latest

