---
- hosts: all
  become: true
  pre_tasks:

  - name: update repo cache (centOS)
    tags: always
    ansible.builtin.yum:
     update_cache: yes
    changed_when: false   # as this play will always update and we won't want it to always output
    when: ansible_distribution == "CentOS"

  - name: update repo cache ( Debian)
    tags: always
    ansible.builtin.apt:
     update_cache: yes
    changed_when: false  # as this play will always update and we won't want it to always output
    when: ansible_distribution == "Debian"
    
- hosts: web_servers
  become: true
  tasks:
    - name: install apache and php for Debian servers
      tags: apache,apache2,debian
      ansible.builtin.apt:
        name: 
         - apache2
         - libapache2-mod-php
        state: latest
      when: ansible_distribution == "Debian"

    - name: install httpd and php for CentOS servers
      tags: centos,httpd
      ansible.builtin.yum:
        name: 
         - httpd
         - php
        state: latest
      when: ansible_distribution == "CentOS"

    - name: start httpd ( CentOS)
      tags: apache,centos,httpd
      service: 
       name: httpd
       state: started
       enabled: yes
      when: ansible_distribution == "CentOS"

    - name: copy default html file for site
      tags: apache,apache2,httpd
      ansible.builtin.copy:
       src: ~/webpage/default_site.html
       dest: /var/www/html/index.html
       owner: root
       group: root
       mode: 0644

    - name: change and email address
      tags: apache,apache2,httpd
      lineinfile:
        path: /etc/httpd/conf/httpd.conf # here is the path we would like to add a line on our server
        regexp: '^ServerAdmin'  # we use the regexpresion to specify the line we want to add a new file
        line: ServerAdmin somebody@somewhere.net # and this is the line we want to add
      when: ansible_distribution == "CentOS"
      register: httpdupdate     # we use register the file using the register with the new name, it could be an arbitary name

    - name: restart httpd
      tags: centos,apache,httpd
      service:
       name: httpd    # here we specify the service 
       state: restarted
      when: httpdupdate is changed  # we use the when statement here as when the httpd is changed, as we have changed in up in the previous play in the register
  
- hosts: workstations
  become: true
  tasks:
    - name: install unzip
      package:
        name: unzip

    - name: install terraform
      unarchive:
        src: https://releases.hashicorp.com/terraform/1.4.4/terraform_1.4.4_linux_amd64.zip
        dest: /usr/local/bin
        remote_src: yes
        mode: 0755
        owner: root
        group: root


- hosts: db_servers
  become: true
  tasks:
    - name: install mariadb package (CentOS)
      tags: mariadb,centos,db
      ansible.builtin.yum:
       name: mariadb
       state: latest
      when: ansible_distribution == "CentOS"

    - name: install mariadb package on (Debian)
      tags: db,mariadb,debian
      ansible.builtin.apt:
       name: mariadb-server
      when: ansible_distribution == "Debian"

- hosts: file_servers
  become: true
  tasks:
    - name: install samba package
      tags: samba
      package: 
       name: samba
       state: latest

